name: GH_Actions_CI
env:
 APPLICATION_NAME    : "MyFlask"
 PACKAGE_NAME        : "flask-deploy-var-${{github.sha}}"
 
# Controls when the action will run. 
on: 
 push:
    branches: [ master ]
jobs:
  my_test:
    runs-on: ubuntu-latest  
    steps:     
     - name : Print Hello Message in testing
       run : echo "Hello world from test jobs"     
         
     - name: Execute few commands
       run: |
        echo "Hello one"
        echo "Hello two"
        echo "Application name: ${{env.APPLICATION_NAME}}"
        
     - name: List current folder
       run: ls -la
       
     - name: Git clone my repo
       uses: actions/checkout@v1 
       
     - name: List current folder
       run: ls -la  
      
  my_deploy:
    runs-on: ubuntu-latest
    needs: my_test
    env:
     var1: "This is JobLevelVar"
     var2: "This is jobLevelVar2"
    steps:
     - name : Print Hello Message     
       run : echo "Hello world from Deploy job"
       
     - name : Print en vars
       run : |
        echo "Var1 = ${{env.VAR1}}"
        echo "Var2 = ${{env.VAR2}}"
        echo "Var3 = $LOCAL_VAR"   
       env:
        LOCAL_VAR: "This super local variable"  
       
     - name: Print deploy message
       run: echo "Deploy package is ${{env.PACKAGE_NAME}}"
       
     - name: Lets test some packages if they are here 1    
       run: aws --version
       
     - name: Lets test some packages if they are here 2   
       run: zip --version
            
    
    
